### ISSUE TITLE
Atomic update on Wallet balance 

### ISSUE THREAD

**Issue by giladTab** [MannikJ/laravel-wallet#12]
Hi 

On TransactionObserver you have this code :

> public function created($transaction)
>     {
>         $transaction->wallet->balance += $transaction->amount;
>         $transaction->wallet->save();
>     }

I suggest to change any balance update to be like  this : 
> public function created($transaction)
>     {
>         $transaction->wallet->increment('balance',$transaction->amount);
>      }

This will  make Atomic update on balance .

**Comment by giladTab** [comment]
I have code ready to be pushed with those changes,

**Comment by MannikJ** [comment]
I guess my latest release does exactly what you suggested.
