### ISSUE TITLE
How to implement multiple wallets for a user

### ISSUE THREAD

**Issue by maverick504** [MannikJ/laravel-wallet#6]
Hi, thanks for building this package!

I have a question, in the repository description, it says _"you can equip your eloquent models with one or multiple digital wallets"_, and that's just what i'm trying to do, but i don't know how.

I would like to add to my project two wallets for the users, like:
- **coins**: that the user can buy via PayPal or credit card).
- **points**: that the user can obtain by completing tasks, like completing their profiles or using the app with regularity, etc.).

I would appreciate if you tell me how can I accomplish that. Thank you very much! ^_^

**Comment by MannikJ** [comment]
Well, sorry for the late reply. It might be too late for you now and my answer is probably not satisfying as well. The HasWallet trait is designed to be used only with a single wallet. 
However, the database model allows to attach multiple wallets to any model inside your app. 
Using the HasWallet trait when there are multiple wallets attached will lead to unpredictable behavior and I would not recommend that. So you will need to write the logic yourself though.
You can start by just adding the appropriate `MorphMany` relation:

```php
public function wallet()
{
    return $this->morphMany(config('wallet.wallet_model', Wallet::class), 'owner');
}
```

You will then also need to add a column to distinguish the wallets. 

I will implement that feature within a few days, so you might wait some time.

**Comment by maverick504** [comment]
Hi! Thanks for the response.

Don't worry, it was just for a personal project that i delayed because i found that i cannot use Stripe on my country and i will have to open a company in the US to accept online payments. I'm planning to continue with that project on the future and if you add that feature, probably i will use your package when i resume the project.

Thanks! (^^)b
